# Generated by Django 3.2.9 on 2021-12-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211202_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customers',
            new_name='customer',
        ),
    ]
